version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '02:00'
  open-pull-requests-limit: 99
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: '02:00'
  open-pull-requests-limit: 99
  allow:
  - dependency-type: indirect
  ignore:
  - dependency-name: none
    versions:
    - ">= 0"
